### ISSUE TITLE
Response given back on GET call should be paginated.

### ISSUE THREAD

**Issue by utsav-techwondoe** [romans91/CommercialDocumentCollector#3]

**Comment by romans91** [comment]
This [commit](https://github.com/romans91/CommercialDocumentCollector/commit/d4390802c60067f81f00f8a248145334580882fe) implements pagination of response contents onto one page. This can serve as a foundation should a more specific pagination strategy be required in the future.

**Comment by romans91** [comment]
Re-opening to implement configurable database-side pagination.

**Comment by romans91** [comment]
@utsav-techwondoe Implemented pagination in [this](https://github.com/romans91/CommercialDocumentCollector/commit/bbfee8e1630988c9091085ebf5add243073a38c3) commit. Hibernate obtains data by executing queries that contain ORDER BY and LIMIT clauses, so there should be no sorting and pagination in the service layer anymore. Let me know if I am incorrect, thanks.
